### PR TITLE
Fix scaling & rotation

### LINKED ISSUE #12: Android camera image is wrong
Hello,
Thanks for this plugin! It's the only one who is really embedded into a flutter app and not just call for external screen and wait for the answer ^^ 

Unfortunately it's not working for me, I test on Android (Mi Mix 2 with Android 8.0.0), here is what I have (portrait and landscape which is even worse as when you move it didn't go the correct way)

device-2018-05-20-172048
device-2018-05-20-172023

And this is a native barcode scanner I have on my phone
device-2018-05-20-172121

Any idea what could be wrong ?

### PR DESCRIPTION
**Pull request by rmtmckenzie**
This should fix #12, #7, #5.

### CODE REVIEW

File: android/src/main/java/com/github/rmtmckenzie/qrmobilevision/QrCameraC2.java [hunk 1]
```diff
@@ -233,27 +227,52 @@ public void stop() {
...
+        }
+
         Size s = sizes[0];
-        if (orientation % 180 == 0) {
-            for (Size size : sizes) {
-                if (size.getHeight() < targetHeight || size.getWidth() < targetWidth) {
-                    break;
+        Size s1 = sizes[1];
+
+        if (s1.getWidth() > s.getWidth() || s1.getHeight() > s.getHeight()) {
```
Comment (csutorasr) [inline android/src/main/java/com/github/rmtmckenzie/qrmobilevision/QrCameraC2.java]: Why not just sort them?

File: lib/QrCamera.dart [hunk 2]
```diff
@@ -1,183 +0,0 @@
-import 'dart:async';
```
Comment (csutorasr) [inline lib/QrCamera.dart]: You should have used `git mv` to rename files. That way the change history should be kept.

File: android/src/main/java/com/github/rmtmckenzie/qrmobilevision/QRReader.java [hunk 3]
```diff
@@ -29,20 +29,21 @@
...
-    QRReader(int width, int height, Context context, int formats, final QRReaderStartedCallback startedCallback, final QRReaderCallbacks communicator,
+    QRReader(int width, int height, Context context, int barcodeFormats, final QRReaderStartedCallback startedCallback, final QRReaderCallbacks communicator,
              final SurfaceTexture texture) {
         this.context = context;
         this.startedCallback = startedCallback;
 
         qrCamera = android.os.Build.VERSION.SDK_INT >= 21 ?
-                new QrCameraC2(width,height,context,texture,new QrDetector(communicator,context, formats)) :
-                new QrCameraC1(width,height,texture,new QrDetector(communicator,context, formats));
+                new QrCameraC2(width, height, context, texture, new QrDetector(communicator, context, barcodeFormats)) :
```
Comment (csutorasr) [inline android/src/main/java/com/github/rmtmckenzie/qrmobilevision/QRReader.java]: It should be nice to have some CI to check linting.
