### PR TITLE
Handle permission denied error on iOS

### LINKED ISSUE #127: Crash on iOS 13 when permission denied
The app crashes on the line 140 of `QrReader.swift`
```swift
    // catch?
    let input = try! AVCaptureDeviceInput.init(device: captureDevice)
```

on iOS 13 when the Camera permission if denied by the user.

```
2020-04-25 21:51:42.472234+0200 Runner[35675:9811013] Initialized TensorFlow Lite runtime.
Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=AVFoundationErrorDomain Code=-11852 "Cannot use Back Camera" UserInfo={NSLocalizedFailureReason=This app is not authorized to use Back Camera., AVErrorDeviceKey=<AVCaptureFigVideoDevice: 0x10870d7c0 [Back Camera][com.apple.avfoundation.avcapturedevice.built-in_video:0]>, NSLocalizedDescription=Cannot use Back Camera}: file /Users/xavier/.pub-cache/hosted/pub.dartlang.org/qr_mobile_vision-1.0.1+1/ios/Classes/QrReader.swift, line 140
2020-04-25 21:51:42.494777+0200 Runner[35675:9811013] Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=AVFoundationErrorDomain Code=-11852 "Cannot use Back Camera" UserInfo={NSLocalizedFailureReason=This app is not authorized to use Back Camera., AVErrorDeviceKey=<AVCaptureFigVideoDevice: 0x10870d7c0 [Back Camera][com.apple.avfoundation.avcapturedevice.built-in_video:0]>, NSLocalizedDescription=Cannot use Back Camera}: file /Users/xavier/.pub-cache/hosted/pub.dartlang.org/qr_mobile_vision-1.0.1+1/ios/Classes/QrReader.swift, line 140
```

Screenshot 2020-04-25 at 21 58 17

### PR DESCRIPTION
**Pull request by xvrh**
Fixes #127 

This PR handles the case where the user refuses the Camera permission on iOS. Previously the app would crash.

63D592A1-6A92-4B4F-A127-ECF3B983D0FB_1_105_c
E32938B8-4DD2-4A4E-9A8A-410E0EC6BAAC_1_105_c

### CODE REVIEW

**Comment by xvrh** [comment]
Hi, @rmtmckenzie 
What do you think of this fix? Is there something else I should do?

File: ios/Classes/QrReader.swift [hunk 1]
```diff
@@ -111,7 +111,7 @@ class QrReader: NSObject {
   let cameraPosition = AVCaptureDevice.Position.back
   let qrCallback: (_:String) -> Void
   
-  init(targetWidth: Int, targetHeight: Int, textureRegistry: FlutterTextureRegistry, options: BarcodeScannerOptions, qrCallback: @escaping (_:String) -> Void) {
```
Comment (howardwkim) [inline ios/Classes/QrReader.swift:114]: Seeing this error `/flutter_qr_mobile_vision/ios/Classes/QrReader.swift:114:95: error: cannot find type 'VisionBarcodeDetectorOptions' in scope`.

Not a Swift guy, but looks like `BarcodeScannerOptions` is defined in the file, so it's unclear to me how it relates to the permission denied error.

I changed it back to `BarcodeScannerOptions` and did not see error again.
